name: Auto Test MS Graph API

on: 
  release:
    types: [published]
  push:
    branches: 
      - main
  schedule:
    - cron: '30 * * * *'
  watch:
    types: [started]
  workflow_dispatch:  # ✅ manually run bhi allow karega

jobs:
  Task:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install requests
      run: pip install requests

    - name: Run API Script
      env:
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python test.py

    - name: Commit refresh token
      run: |
        git config --global user.email testApi@chrisvcg.top
        git config --global user.name testApiBot
        git add .
        git commit -m "update new refresh token with testApiBot" -a || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
